Repository headwirecom/peregrine-cms, pull requests merged in 2020-12, with the labels that each got.

#666 Issues/663: fix not being able to drop components into blank page
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/contentview/template.vue
Labels: HIGH!, bug

#669 Fix com.peregrine.slingjunit.localFS.LocalFSJTest
  slingjunit.parent/README.md
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/localFS/LocalFSJTest.java
Labels: enhancement, refactoring, replication

#670 Fix inconsistent UX of delete operation
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/assetview/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/componentexplorer/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/objectview/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/pageview/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/templateview/template.vue
Labels: UX/UI, e2e-test-available, enhancement

#667 selection is now cleared upon changing components (#639)
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/contentview/template.vue
  admin-base/ui.apps/src/main/js/utils.js
Labels: bug, e2e-test-available

#680 fix for #679
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/contentview/template.vue
  pagerenderer/vue/ui.apps/package-lock.json
Labels: bug, e2e-test-available
