Repository headwirecom/peregrine-cms, pull requests merged in 2021-02, with the labels that each got.

#653 Remove unused imports
  admin-base/core/src/main/java/com/peregrine/admin/resource/ReferenceListerService.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ComponentDefinitionServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ListResourceVersionsServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReferenceListerServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/RestoreRecyclableServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/UserPreferencesServlet.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PerPageImpl.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PeregrineAdapterFactory.java
  platform/base/core/src/main/java/com/peregrine/rendition/RenditionsServlet.java
  platform/base/core/src/main/java/com/peregrine/replication/Reference.java
  platform/base/core/src/main/java/com/peregrine/transform/ImageTransformationSetup.java
  platform/base/core/src/main/java/com/peregrine/transform/operation/GreyscaleImageTransformation.java
  platform/commons/src/main/java/com/peregrine/commons/servlets/AbstractBaseServlet.java
  platform/commons/src/test/java/com/peregrine/TestingTools.java
  platform/commons/src/test/java/com/peregrine/commons/json/JSonFormatterTest.java
  platform/commons/src/test/java/com/peregrine/commons/servlets/ServletHelperTest.java
  platform/commons/src/test/java/com/peregrine/mock/MockTools.java
  platform/felib/core/src/main/java/com/peregrine/felib/models/CSSModel.java
  platform/felib/core/src/main/java/com/peregrine/felib/models/JCRFile.java
  platform/felib/core/src/main/java/com/peregrine/felib/models/JSModel.java
  platform/replication/core/src/main/java/com/peregrine/admin/replication/impl/DistributionEventHandlerService.java
  platform/replication/core/src/main/java/com/peregrine/admin/replication/impl/DistributionReplicationService.java
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/ReferencesJTest.java
Labels: refactoring

#710 Fix: publishing secondary items causes js error
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/TenantSetupReplicationServlet.java
  platform/base/core/src/main/java/com/peregrine/adaption/PerBase.java
  platform/base/core/src/main/java/com/peregrine/adaption/PerReplicable.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PerBaseImpl.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PerReplicableImpl.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PeregrineAdapterFactory.java
  platform/base/core/src/main/resources/SLING-INF/nodetypes/replication.cnd
  platform/commons/src/main/java/com/peregrine/commons/util/PerUtil.java
Labels: replication

#654 Remove unused Model Factory references
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ContentServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/CreateFolderServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/CreateObjectDefinitionServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/CreateObjectServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/CreateTemplateServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/DeleteTenantServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/InsertNodeAt.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/MoveNodeTo.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/NodeServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/UploadFilesServlet.java
Labels: refactoring

#717 Remove replication module
  admin-base/core/pom.xml
  admin-base/core/src/main/java/com/peregrine/admin/servlets/AdminPaths.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/DeleteNodeServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/DeletePageServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ListReplicationStatusServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/MoveServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/NodesServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReferenceListerServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReferencedByListerServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationListServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServletBase.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/TenantSetupReplicationServlet.java
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config.author/com.peregrine.replication.DefaultReplicationMapperService-simple.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config.exmaple/com.peregrine.replication.impl.RemoteS3SystemReplicationService-local.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config.live/com.peregrine.replication.DefaultReplicationMapperService-simple.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/com.peregrine.replication.DefaultReplicationMapperService-simple.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/com.peregrine.replication.impl.DistributionReplicationService-remote.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/com.peregrine.replication.impl.ImageMetadataSelectorService-iccProfile.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/com.peregrine.replication.impl.ImageMetadataSelectorService-pngIhdr.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/com.peregrine.replication.impl.LocalFileSystemReplicationService-local.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/com.peregrine.replication.impl.LocalReplicationService-local.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/runmodes/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-distributionEventHandler.xml
  docs/public/distribution/index.md
  platform/base/core/pom.xml
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PeregrineAdapterFactory.java
  platform/base/core/src/main/java/com/peregrine/replication/DefaultReplicationMapper.java
  platform/base/core/src/main/java/com/peregrine/replication/DefaultReplicationMapperService.java
  platform/base/core/src/main/java/com/peregrine/replication/ImageMetadataSelector.java
  platform/base/core/src/main/java/com/peregrine/replication/PerReplicable.java
  platform/base/core/src/main/java/com/peregrine/replication/Reference.java
  platform/base/core/src/main/java/com/peregrine/replication/Replication.java
  platform/base/core/src/main/java/com/peregrine/replication/ReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/ReplicationUtil.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/DistributionEvent.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/DistributionEventHandlerService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/DistributionReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/FileReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ImageMetadataSelectorService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalFileSystemReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalFileSystemSiteMapReplication.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ModPageSpeedCacheInvalidationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/PerReplicableImpl.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ReplicationMixinNodeTypesOverride.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ReplicationsContainerImpl.java
  platform/base/core/src/test/java/com/peregrine/replication/DefaultReplicationConfigTest.java
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.ReplicationMixinNodeTypesOverride.xml
  platform/pom.xml
  platform/replication/core/pom.xml
  platform/replication/core/src/main/java/com/peregrine/admin/replication/ReplicationConstants.java
  platform/replication/pom.xml
  platform/replication/ui.apps/pom.xml
  pom.xml
  slingjunit.parent/core/pom.xml
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/ReferencesJTest.java
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/author/RemoteReplAuthorJTest.java
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/localFS/LocalFSJTest.java
  testing/testing.config.client/src/main/resources/SLING-INF/apps/it/runmodes/config.it/com.peregrine.replication.impl.LocalReplicationService-it.json
Labels: HIGH!, bug, enhancement, refactoring, replication, sling12

#736 Create paths before adding permissions onto them
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-peregrine.config
Labels: HIGH!, bug, fixed, sling12

#737 Fix #726: creating a new component through keyboard shortcuts sets the current inline edit text to undefined
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/contentview/template.vue
Labels: bug

#728 fix #498 logged in as username display issues
  admin-base/core/src/main/java/com/peregrine/admin/servlets/AccessServlet.java
  admin-base/materialize/custom/_navbar.scss
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/nav/template.vue
  admin-base/ui.apps/src/main/js/apiImpl.js
Labels: UX/UI, bug

#742 Remove redundant stuff in the way of cleaner replication
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServlet.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PeregrineAdapterFactory.java
  platform/base/core/src/main/java/com/peregrine/render/RenderService.java
  platform/base/core/src/main/java/com/peregrine/replication/DefaultReplicationMapperService.java
  platform/base/core/src/main/java/com/peregrine/replication/ReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/DistributionReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/FileReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalFileSystemReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalReplicationService.java
  platform/commons/src/main/java/com/peregrine/commons/ResourceUtils.java
  platform/commons/src/main/java/com/peregrine/commons/TextUtils.java
  platform/commons/src/main/java/com/peregrine/commons/util/PerUtil.java
  platform/commons/src/test/java/com/peregrine/commons/TextUtilsTest.java
Labels: HIGH!, bug, enhancement, fixed, refactoring, replication, sling12

#738 Add links to configs in distribution docs
  docs/public/distribution/index.md
Labels: HIGH!, bug, enhancement, fixed, replication, sling12

#739 Simplify aspects of replication FE
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServlet.java
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/perapi/definitions/admin.yaml
  admin-base/ui.apps/src/main/js/api.js
  admin-base/ui.apps/src/main/js/apiImpl.js
  admin-base/ui.apps/src/main/js/stateActions/publish.js
  admin-base/ui.apps/src/main/js/stateActions/unreplicate.js
Labels: HIGH!, bug, enhancement, fixed, refactoring, replication, sling12

#763 Fix: #613 links in text editor
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/contentview/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/richtoolbar/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/richtoolbargroup/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/subnav/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/field/texteditor/template.vue
Labels: UX/UI, bug, rich-text-editor
