Repository headwirecom/peregrine-cms, pull requests merged in 2021-03, with the labels that each got.

#766 enhancement #725: upload files return is now a result of the uploaded files
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/filedropper/template.vue
  admin-base/ui.apps/src/main/js/apiImpl.js
  admin-base/ui.apps/src/main/js/perAdminApp.js
  admin-base/ui.apps/src/main/js/stateActions/uploadFiles.js
  admin-base/ui.apps/src/main/js/utils.js
  admin-base/ui.apps/src/main/js/utils/notifier.js
Labels: enhancement, refactoring

#743 Allow per:Object in ReplicationMixinNodeTypesOverride
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.ReplicationMixinNodeTypesOverride.xml
Labels: HIGH!, bug, enhancement, fixed, replication

#768 fix #767: show minimalistic loading animation for references
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/linearpreloader/.content.xml
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/linearpreloader/template.vue
Labels: UX/UI, bug

#769 fix #254: resolve some issues all around "objects"
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/field/collection/template.vue
  admin-base/ui.apps/src/main/js/stateActions/createObject.js
  admin-base/ui.apps/src/main/js/stateActions/editObject.js
  admin-base/ui.apps/src/main/js/stateActions/saveObjectEdit.js
  admin-base/ui.apps/src/main/js/stateActions/selectObject.js
Labels: bug

#785 Fix status after publishing an object
  .gitignore
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/publishinginfo/template.vue
Labels: UX/UI, bug, fixed, replication, sling12

#781 Implement: unhide child pages from sitemap
  pagerenderer/vue/ui.apps/src/main/content/jcr_root/apps/pagerendervue/structure/page/explorer_dialog.json
  platform/base/core/src/main/java/com/peregrine/sitemap/PageRecognizer.java
  platform/base/core/src/main/java/com/peregrine/sitemap/PageRecognizerBase.java
  platform/base/core/src/main/java/com/peregrine/sitemap/SiteMapExtractorBase.java
  platform/base/core/src/main/java/com/peregrine/sitemap/impl/PerPageRecognizerBase.java
  platform/base/core/src/test/java/com/peregrine/sitemap/PageRecognizerBaseTest.java
  platform/commons/src/main/java/com/peregrine/commons/util/PerConstants.java
Labels: enhancement, sitemap, sling12, versioning

#733 Add modification time on deleteResource
  admin-base/core/src/main/java/com/peregrine/admin/resource/AdminResourceHandlerService.java
Labels: bug, enhancement, fixed, replication, sling12

#756 Move replication runmodes to platform's ui.apps
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config.author/com.peregrine.replication.DefaultReplicationMapperService-simple.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config.example/com.peregrine.replication.impl.RemoteS3SystemReplicationService-local.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config.live/com.peregrine.replication.DefaultReplicationMapperService-simple.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.DefaultReplicationMapperService-simple.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.DistributionReplicationService-remote.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.ImageMetadataSelectorService-iccProfile.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.ImageMetadataSelectorService-pngIhdr.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.LocalFileSystemReplicationService-local.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/com.peregrine.replication.impl.LocalReplicationService-local.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-distributionAgentService.xml
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-distributionEventHandler.xml
Labels: refactoring, replication, sling12

#805 fix #254: issues regarding collections
  admin-base/ui.apps/src/main/content/jcr_root/apps/field/collection/template.vue
Labels: bug

#817 Fix textarea scroll
  admin-base/materialize/custom/_vue-form-generator.scss
Labels: bug

#757 Create paths before adding permissions onto them
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config/org.apache.sling.jcr.repoinit.RepositoryInitializer-peregrine.config
Labels: bug, replication, sling12

#826 fix: editable-actions visiblity on component select
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/contentview/template.vue
Labels: HIGH!, bug
