Repository headwirecom/peregrine-cms, pull requests merged in 2021-04, with the labels that each got.

#830 Move ReferenceListerService to platform/base/core
  admin-base/core/src/main/java/com/peregrine/admin/resource/ResourceRelocationService.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReferenceListerServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReferencedByListerServlet.java
  admin-base/core/src/test/java/com/peregrine/admin/resource/TreeTest.java
  platform/base/core/pom.xml
  platform/base/core/src/main/java/com/peregrine/reference/Reference.java
  platform/base/core/src/main/java/com/peregrine/reference/ReferenceLister.java
  platform/base/core/src/main/java/com/peregrine/render/impl/ReferenceListerService.java
  platform/base/core/src/main/java/com/peregrine/replication/DefaultReplicationMapperService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/DistributionReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/FileReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalFileSystemReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ModPageSpeedCacheInvalidationService.java
  platform/base/ui.apps/src/main/content/jcr_root/apps/runmodes/config.example/com.peregrine.replication.impl.RemoteS3SystemReplicationService-local.xml
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/ReferencesJTest.java
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/VersionsJTest.java
Labels: refactoring, replication, sling12

#753 Remove startup exception from ReplicationMixinNodeTypesOverride
  platform/base/core/src/main/java/com/peregrine/replication/impl/ReplicationMixinNodeTypesOverride.java
Labels: enhancement, fixed, replication, sling12

#834 fix #832: vfg groups should now behave propery
  admin-base/materialize/custom/_vue-form-generator.scss
  admin-base/materialize/custom/_workspace.scss
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/componentexplorer/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/editor/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/workspace/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/field/collection/template.vue
  admin-base/ui.apps/src/main/content/jcr_root/apps/field/material-range/template.vue
  admin-base/ui.apps/src/main/js/apiImpl.js
Labels: bug

#773 Fix: assets do not replicate properly (+ side quests found in the process)
  admin-base/core/pom.xml
  admin-base/core/src/main/java/com/peregrine/admin/servlets/NodesServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServletBase.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/TenantSetupReplicationServlet.java
  admin-base/core/src/test/java/com/peregrine/admin/servlets/ReplicationServletTest.java
  admin-base/core/src/test/java/com/peregrine/admin/servlets/ReplicationServletTestBase.java
  admin-base/core/src/test/java/com/peregrine/admin/servlets/TenantSetupReplicationServletTest.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PeregrineAdapterFactory.java
  platform/base/core/src/main/java/com/peregrine/replication/PerReplicable.java
  platform/base/core/src/main/java/com/peregrine/replication/ReplicationUtil.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/FileReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalFileSystemReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/PerReplicableImpl.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ReplicationsContainerWithDefaultImpl.java
  platform/base/core/src/test/java/com/peregrine/replication/ReplicationUtilTest.java
  platform/base/core/src/test/java/com/peregrine/replication/impl/LocalFileSystemReplicationServiceTest.java
  platform/base/core/src/test/java/com/peregrine/replication/impl/PerReplicableImplTest.java
  platform/base/core/src/test/java/com/peregrine/sitemap/PageRecognizerBaseTest.java
  platform/base/core/src/test/java/com/peregrine/sitemap/impl/NonEmptyPerPageRecognizerTest.java
  platform/base/core/src/test/java/com/peregrine/sitemap/impl/SiteMapUrlBuilderImplTest.java
  platform/commons/src/main/java/com/peregrine/commons/IOUtils.java
  platform/commons/src/main/java/com/peregrine/commons/ResourceUtils.java
  platform/commons/src/main/java/com/peregrine/commons/util/PerUtil.java
  platform/commons/src/test/java/com/peregrine/SlingResourcesTest.java
  platform/commons/src/test/java/com/peregrine/commons/IOUtilsTest.java
  platform/commons/src/test/java/com/peregrine/commons/ResourceUtilsTest.java
  platform/commons/src/test/java/com/peregrine/mock/PageContentMock.java
  platform/commons/src/test/java/com/peregrine/mock/PageMock.java
  platform/commons/src/test/java/com/peregrine/mock/RepoMock.java
  platform/commons/src/test/java/com/peregrine/mock/ResourceMock.java
  platform/commons/src/test/java/com/peregrine/mock/SiteMock.java
  platform/commons/src/test/java/com/peregrine/mock/SlingHttpServletRequestMock.java
Labels: HIGH!, bug, enhancement, fixed, refactoring, replication, sling12

#860 Fix: tenant site setup replication NPE + slow LocalReplicationService
  admin-base/core/pom.xml
  admin-base/core/src/main/java/com/peregrine/admin/servlets/ReplicationServlet.java
  admin-base/core/src/main/java/com/peregrine/admin/servlets/TenantSetupReplicationServlet.java
  platform/base/core/pom.xml
  platform/base/core/src/main/java/com/peregrine/reference/ReferenceLister.java
  platform/base/core/src/main/java/com/peregrine/render/impl/ReferenceListerService.java
  platform/base/core/src/main/java/com/peregrine/replication/DefaultReplicationMapperService.java
  platform/base/core/src/main/java/com/peregrine/replication/Replication.java
  platform/base/core/src/main/java/com/peregrine/replication/ReplicationUtil.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/DistributionReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/FileReplicationServiceBase.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/LocalReplicationService.java
  platform/base/core/src/main/java/com/peregrine/replication/impl/ModPageSpeedCacheInvalidationService.java
  platform/commons/pom.xml
  platform/commons/src/main/java/com/peregrine/commons/util/PerUtil.java
  pom.xml
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/author/RemoteReplAuthorJTest.java
  slingjunit.parent/core/src/main/java/com/peregrine/slingjunit/localFS/LocalFSJTest.java
Labels: bug, fixed, replication, sling12

#878 Fix update servlet on restricted properties
  admin-base/core/src/main/java/com/peregrine/admin/resource/AdminResourceHandlerService.java
Labels: replication

#879 Add modification time uniformly to all resources
  platform/base/core/src/main/java/com/peregrine/adaption/PerPage.java
  platform/base/core/src/main/java/com/peregrine/adaption/impl/PerPageImpl.java
  platform/base/core/src/main/java/com/peregrine/rendition/BaseResourceHandlerService.java
  platform/commons/src/main/java/com/peregrine/commons/util/PerUtil.java
Labels: replication

#889 Tie the globe icon button to publishing modal window
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorer/template.vue
Labels: replication

#880 Refresh view after 'Properties & Information' changes
  admin-base/ui.apps/src/main/content/jcr_root/apps/admin/components/explorerpreviewcontent/template.vue
Labels: replication
